package com.agentgame.one.engine.agent

import org.json.JSONArray
import org.json.JSONObject

/** A single tool invocation the agent plans. */
data class ToolCall(val tool: String, val args: Map<String, Any?>)

/** A named group of tool calls forming one step. */
data class AgentStep(val title: String, val toolCalls: List<ToolCall>)

/** The agent's plan for a goal. */
data class AgentPlan(val goal: String, val steps: List<AgentStep>, val summary: String)

/**
 * Turns a goal into a concrete plan. Uses the LLM when configured; otherwise falls back to an
 * offline heuristic that understands the sample project (main.tscn + player.gs).
 */
interface AgentPlanner {
    fun plan(ctx: AgentContext, goal: String): AgentPlan

    /** Asks the planner whether more work is needed after executing the plan (agentic loop). */
    fun nextActions(ctx: AgentContext, goal: String): List<ToolCall>
}

class HeuristicPlanner : AgentPlanner {

    override fun plan(ctx: AgentContext, goal: String): AgentPlan {
        val g = goal.lowercase()
        val steps = mutableListOf<AgentStep>()

        steps.add(AgentStep(
            "Explore the workspace",
            listOf(
                ToolCall("list_files", emptyMap()),
                ToolCall("read_file", mapOf("path" to "README.md")),
                ToolCall("read_file", mapOf("path" to "main.tscn")),
            )
        ))

        when {
            g.contains("coin") || g.contains("pickup") || g.contains("collect") -> {
                steps.add(AgentStep(
                    "Add a collectible coin to the scene",
                    listOf(
                        ToolCall("add_to_context", mapOf("path" to "main.tscn")),
                        ToolCall("edit_file", mapOf(
                            "path" to "main.tscn",
                            "search" to "[node type=\"RigidBody2D\" name=\"Player\" parent=\"Main\"]",
                            "replace" to "[node type=\"RigidBody2D\" name=\"Player\" parent=\"Main\"]\n[node type=\"Area2D\" name=\"Coin\" parent=\"Main\"]\nposition = Vector2(160, 200)",
                        )),
                        ToolCall("write_file", mapOf(
                            "path" to "coin.gs",
                            "content" to "var collected = false\nfunc _process(delta):\n    self.rotation += 3 * delta\n",
                        )),
                    )
                ))
            }
            g.contains("speed") || g.contains("move") || g.contains("faster") || g.contains("run") -> {
                steps.add(AgentStep(
                    "Tune the player movement speed",
                    listOf(
                        ToolCall("add_to_context", mapOf("path" to "player.gs")),
                        ToolCall("edit_file", mapOf(
                            "path" to "player.gs",
                            "search" to "var speed = 220",
                            "replace" to "var speed = 320",
                        )),
                    )
                ))
            }
            g.contains("jump") || g.contains("higher") -> {
                steps.add(AgentStep(
                    "Increase the player jump strength",
                    listOf(
                        ToolCall("add_to_context", mapOf("path" to "player.gs")),
                        ToolCall("edit_file", mapOf(
                            "path" to "player.gs",
                            "search" to "var jump = 560",
                            "replace" to "var jump = 760",
                        )),
                    )
                ))
            }
            g.contains("enemy") || g.contains("hazard") || g.contains("danger") -> {
                steps.add(AgentStep(
                    "Add a hazard to the scene",
                    listOf(
                        ToolCall("edit_file", mapOf(
                            "path" to "main.tscn",
                            "search" to "[node type=\"Camera2D\" name=\"Camera\" parent=\"Main\"]",
                            "replace" to "[node type=\"Camera2D\" name=\"Camera\" parent=\"Main\"]\n[node type=\"Area2D\" name=\"Hazard\" parent=\"Main\"]\nposition = Vector2(0, 240)",
                        )),
                        ToolCall("write_file", mapOf(
                            "path" to "hazard.gs",
                            "content" to "func _process(delta):\n    # hazard logic\n    pass\n",
                        )),
                    )
                ))
            }
            else -> {
                steps.add(AgentStep(
                    "Implement the requested feature",
                    listOf(
                        ToolCall("write_file", mapOf(
                            "path" to "feature.gs",
                            "content" to "# Generated by the AI agent for: $goal\nfunc _ready():\n    print(\"feature ready\")\n",
                        )),
                    )
                ))
            }
        }

        steps.add(AgentStep(
            "Verify the changes",
            listOf(
                ToolCall("run_command", mapOf("command" to "ls")),
                ToolCall("run_command", mapOf("command" to "cat player.gs")),
            )
        ))

        return AgentPlan(goal, steps, "Heuristic plan with ${steps.size} steps")
    }

    override fun nextActions(ctx: AgentContext, goal: String): List<ToolCall> = emptyList()
}

class LlmPlanner(private val client: LlmClient, private val fallback: AgentPlanner = HeuristicPlanner()) : AgentPlanner {

    override fun plan(ctx: AgentContext, goal: String): AgentPlan {
        if (!client.configured) return fallback.plan(ctx, goal)
        val system = "You are a game dev agent planning changes to a Godot-style project. " +
            "Return ONLY a JSON object: {\"steps\":[{\"title\":\"...\",\"actions\":[{\"tool\":\"edit_file\",\"args\":{\"path\":\"main.tscn\",\"search\":\"...\",\"replace\":\"...\"}}]}]}. " +
            "Available tools: list_files, read_file, write_file, edit_file, search_files, add_to_context, run_command. Be concrete and minimal."
        val user = "Goal: $goal\n\n${ctx.projectSummary()}\n\nPlan the steps."
        val raw = client.chat(system, user) ?: return fallback.plan(ctx, goal)
        return try {
            val json = extractJson(raw)
            val stepsArr = json.getJSONArray("steps")
            val steps = mutableListOf<AgentStep>()
            for (i in 0 until stepsArr.length()) {
                val s = stepsArr.getJSONObject(i)
                val title = s.optString("title", "Step ${i + 1}")
                val actions = mutableListOf<ToolCall>()
                val arr = s.optJSONArray("actions") ?: JSONArray()
                for (j in 0 until arr.length()) {
                    val a = arr.getJSONObject(j)
                    val tool = a.optString("tool", "read_file")
                    val args = mutableMapOf<String, Any?>()
                    val argsObj = a.optJSONObject("args")
                    if (argsObj != null) {
                        for (k in argsObj.keys()) args[k] = argsObj.opt(k)
                    }
                    actions.add(ToolCall(tool, args))
                }
                steps.add(AgentStep(title, actions))
            }
            AgentPlan(goal, steps, "LLM-generated plan with ${steps.size} steps")
        } catch (t: Throwable) {
            fallback.plan(ctx, goal)
        }
    }

    override fun nextActions(ctx: AgentContext, goal: String): List<ToolCall> {
        if (!client.configured) return fallback.nextActions(ctx, goal)
        val system = "You are a game dev agent. Based on the work so far, decide the next tool calls to finish: $goal. " +
            "Return ONLY JSON: {\"actions\":[{\"tool\":\"...\",\"args\":{}}]} or {\"actions\":[]} if done."
        val recent = ctx.conversation.takeLast(12).joinToString("\n") { "${it.role}: ${it.content.take(800)}" }
        val raw = client.chat(system, recent) ?: return emptyList()
        return try {
            val json = extractJson(raw)
            val arr = json.getJSONArray("actions")
            val out = mutableListOf<ToolCall>()
            for (i in 0 until arr.length()) {
                val a = arr.getJSONObject(i)
                val tool = a.optString("tool", "read_file")
                val args = mutableMapOf<String, Any?>()
                val argsObj = a.optJSONObject("args")
                if (argsObj != null) for (k in argsObj.keys()) args[k] = argsObj.opt(k)
                out.add(ToolCall(tool, args))
            }
            out
        } catch (t: Throwable) { emptyList() }
    }

    private fun extractJson(raw: String): JSONObject {
        val start = raw.indexOf('{')
        val end = raw.lastIndexOf('}')
        if (start >= 0 && end > start) return JSONObject(raw.substring(start, end + 1))
        return JSONObject(raw)
    }
}
